
namespace MediCode
{
    partial class Drugs
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Drugs));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.updateButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.reportsButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.deleteButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.drugsGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.quantityTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.drugIdTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dosageLabel = new System.Windows.Forms.Label();
            this.quantityLabel = new System.Windows.Forms.Label();
            this.nameLabel = new System.Windows.Forms.Label();
            this.drugIdLabel = new System.Windows.Forms.Label();
            this.backButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dosageTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.prescriptionIdLabel = new System.Windows.Forms.Label();
            this.prescriptionIdTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.drugsGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // updateButton
            // 
            this.updateButton.AllowAnimations = true;
            this.updateButton.AllowMouseEffects = true;
            this.updateButton.AllowToggling = false;
            this.updateButton.AnimationSpeed = 200;
            this.updateButton.AutoGenerateColors = false;
            this.updateButton.AutoRoundBorders = false;
            this.updateButton.AutoSizeLeftIcon = true;
            this.updateButton.AutoSizeRightIcon = true;
            this.updateButton.BackColor = System.Drawing.Color.Transparent;
            this.updateButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("updateButton.BackgroundImage")));
            this.updateButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.ButtonText = "Update";
            this.updateButton.ButtonTextMarginLeft = 0;
            this.updateButton.ColorContrastOnClick = 45;
            this.updateButton.ColorContrastOnHover = 45;
            this.updateButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.updateButton.CustomizableEdges = borderEdges1;
            this.updateButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.updateButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.updateButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.updateButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.updateButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.updateButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.updateButton.IconMarginLeft = 11;
            this.updateButton.IconPadding = 10;
            this.updateButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.updateButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.updateButton.IconSize = 25;
            this.updateButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.IdleBorderRadius = 1;
            this.updateButton.IdleBorderThickness = 1;
            this.updateButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.IdleIconLeftImage = null;
            this.updateButton.IdleIconRightImage = null;
            this.updateButton.IndicateFocus = false;
            this.updateButton.Location = new System.Drawing.Point(460, 273);
            this.updateButton.Name = "updateButton";
            this.updateButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.OnDisabledState.BorderRadius = 1;
            this.updateButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnDisabledState.BorderThickness = 1;
            this.updateButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.OnDisabledState.IconLeftImage = null;
            this.updateButton.OnDisabledState.IconRightImage = null;
            this.updateButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.onHoverState.BorderRadius = 1;
            this.updateButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.onHoverState.BorderThickness = 1;
            this.updateButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.updateButton.onHoverState.IconLeftImage = null;
            this.updateButton.onHoverState.IconRightImage = null;
            this.updateButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnIdleState.BorderRadius = 1;
            this.updateButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnIdleState.BorderThickness = 1;
            this.updateButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.updateButton.OnIdleState.IconLeftImage = null;
            this.updateButton.OnIdleState.IconRightImage = null;
            this.updateButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.BorderRadius = 1;
            this.updateButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnPressedState.BorderThickness = 1;
            this.updateButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.updateButton.OnPressedState.IconLeftImage = null;
            this.updateButton.OnPressedState.IconRightImage = null;
            this.updateButton.Size = new System.Drawing.Size(75, 40);
            this.updateButton.TabIndex = 53;
            this.updateButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.updateButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.updateButton.TextMarginLeft = 0;
            this.updateButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.updateButton.UseDefaultRadiusAndThickness = true;
            this.updateButton.Click += new System.EventHandler(this.updateButton_Click);
            // 
            // reportsButton
            // 
            this.reportsButton.AllowAnimations = true;
            this.reportsButton.AllowMouseEffects = true;
            this.reportsButton.AllowToggling = false;
            this.reportsButton.AnimationSpeed = 200;
            this.reportsButton.AutoGenerateColors = false;
            this.reportsButton.AutoRoundBorders = false;
            this.reportsButton.AutoSizeLeftIcon = true;
            this.reportsButton.AutoSizeRightIcon = true;
            this.reportsButton.BackColor = System.Drawing.Color.Transparent;
            this.reportsButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.reportsButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("reportsButton.BackgroundImage")));
            this.reportsButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.ButtonText = "Reports";
            this.reportsButton.ButtonTextMarginLeft = 0;
            this.reportsButton.ColorContrastOnClick = 45;
            this.reportsButton.ColorContrastOnHover = 45;
            this.reportsButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.reportsButton.CustomizableEdges = borderEdges2;
            this.reportsButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.reportsButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportsButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportsButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportsButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.reportsButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.reportsButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.reportsButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.reportsButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.reportsButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.reportsButton.IconMarginLeft = 11;
            this.reportsButton.IconPadding = 10;
            this.reportsButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.reportsButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.reportsButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.reportsButton.IconSize = 25;
            this.reportsButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.IdleBorderRadius = 1;
            this.reportsButton.IdleBorderThickness = 1;
            this.reportsButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.reportsButton.IdleIconLeftImage = null;
            this.reportsButton.IdleIconRightImage = null;
            this.reportsButton.IndicateFocus = false;
            this.reportsButton.Location = new System.Drawing.Point(695, 12);
            this.reportsButton.Name = "reportsButton";
            this.reportsButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportsButton.OnDisabledState.BorderRadius = 1;
            this.reportsButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.OnDisabledState.BorderThickness = 1;
            this.reportsButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportsButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportsButton.OnDisabledState.IconLeftImage = null;
            this.reportsButton.OnDisabledState.IconRightImage = null;
            this.reportsButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.onHoverState.BorderRadius = 1;
            this.reportsButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.onHoverState.BorderThickness = 1;
            this.reportsButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.reportsButton.onHoverState.IconLeftImage = null;
            this.reportsButton.onHoverState.IconRightImage = null;
            this.reportsButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.OnIdleState.BorderRadius = 1;
            this.reportsButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.OnIdleState.BorderThickness = 1;
            this.reportsButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.reportsButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.reportsButton.OnIdleState.IconLeftImage = null;
            this.reportsButton.OnIdleState.IconRightImage = null;
            this.reportsButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.OnPressedState.BorderRadius = 1;
            this.reportsButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.OnPressedState.BorderThickness = 1;
            this.reportsButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.reportsButton.OnPressedState.IconLeftImage = null;
            this.reportsButton.OnPressedState.IconRightImage = null;
            this.reportsButton.Size = new System.Drawing.Size(75, 40);
            this.reportsButton.TabIndex = 52;
            this.reportsButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.reportsButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.reportsButton.TextMarginLeft = 0;
            this.reportsButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.reportsButton.UseDefaultRadiusAndThickness = true;
            this.reportsButton.Click += new System.EventHandler(this.reportsButton_Click);
            // 
            // deleteButton
            // 
            this.deleteButton.AllowAnimations = true;
            this.deleteButton.AllowMouseEffects = true;
            this.deleteButton.AllowToggling = false;
            this.deleteButton.AnimationSpeed = 200;
            this.deleteButton.AutoGenerateColors = false;
            this.deleteButton.AutoRoundBorders = false;
            this.deleteButton.AutoSizeLeftIcon = true;
            this.deleteButton.AutoSizeRightIcon = true;
            this.deleteButton.BackColor = System.Drawing.Color.Transparent;
            this.deleteButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteButton.BackgroundImage")));
            this.deleteButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.ButtonText = "Delete";
            this.deleteButton.ButtonTextMarginLeft = 0;
            this.deleteButton.ColorContrastOnClick = 45;
            this.deleteButton.ColorContrastOnHover = 45;
            this.deleteButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.deleteButton.CustomizableEdges = borderEdges3;
            this.deleteButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deleteButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.deleteButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.deleteButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.deleteButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deleteButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deleteButton.IconMarginLeft = 11;
            this.deleteButton.IconPadding = 10;
            this.deleteButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deleteButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deleteButton.IconSize = 25;
            this.deleteButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.IdleBorderRadius = 1;
            this.deleteButton.IdleBorderThickness = 1;
            this.deleteButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.IdleIconLeftImage = null;
            this.deleteButton.IdleIconRightImage = null;
            this.deleteButton.IndicateFocus = false;
            this.deleteButton.Location = new System.Drawing.Point(569, 273);
            this.deleteButton.Name = "deleteButton";
            this.deleteButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteButton.OnDisabledState.BorderRadius = 1;
            this.deleteButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnDisabledState.BorderThickness = 1;
            this.deleteButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteButton.OnDisabledState.IconLeftImage = null;
            this.deleteButton.OnDisabledState.IconRightImage = null;
            this.deleteButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.onHoverState.BorderRadius = 1;
            this.deleteButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.onHoverState.BorderThickness = 1;
            this.deleteButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deleteButton.onHoverState.IconLeftImage = null;
            this.deleteButton.onHoverState.IconRightImage = null;
            this.deleteButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnIdleState.BorderRadius = 1;
            this.deleteButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnIdleState.BorderThickness = 1;
            this.deleteButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.deleteButton.OnIdleState.IconLeftImage = null;
            this.deleteButton.OnIdleState.IconRightImage = null;
            this.deleteButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnPressedState.BorderRadius = 1;
            this.deleteButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnPressedState.BorderThickness = 1;
            this.deleteButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deleteButton.OnPressedState.IconLeftImage = null;
            this.deleteButton.OnPressedState.IconRightImage = null;
            this.deleteButton.Size = new System.Drawing.Size(75, 40);
            this.deleteButton.TabIndex = 51;
            this.deleteButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.deleteButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deleteButton.TextMarginLeft = 0;
            this.deleteButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.deleteButton.UseDefaultRadiusAndThickness = true;
            this.deleteButton.Click += new System.EventHandler(this.deleteButton_Click);
            // 
            // addButton
            // 
            this.addButton.AllowAnimations = true;
            this.addButton.AllowMouseEffects = true;
            this.addButton.AllowToggling = false;
            this.addButton.AnimationSpeed = 200;
            this.addButton.AutoGenerateColors = false;
            this.addButton.AutoRoundBorders = false;
            this.addButton.AutoSizeLeftIcon = true;
            this.addButton.AutoSizeRightIcon = true;
            this.addButton.BackColor = System.Drawing.Color.Transparent;
            this.addButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addButton.BackgroundImage")));
            this.addButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.ButtonText = "Add";
            this.addButton.ButtonTextMarginLeft = 0;
            this.addButton.ColorContrastOnClick = 45;
            this.addButton.ColorContrastOnHover = 45;
            this.addButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.addButton.CustomizableEdges = borderEdges4;
            this.addButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.addButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.addButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addButton.IconMarginLeft = 11;
            this.addButton.IconPadding = 10;
            this.addButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addButton.IconSize = 25;
            this.addButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.IdleBorderRadius = 1;
            this.addButton.IdleBorderThickness = 1;
            this.addButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.IdleIconLeftImage = null;
            this.addButton.IdleIconRightImage = null;
            this.addButton.IndicateFocus = false;
            this.addButton.Location = new System.Drawing.Point(350, 273);
            this.addButton.Name = "addButton";
            this.addButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addButton.OnDisabledState.BorderRadius = 1;
            this.addButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnDisabledState.BorderThickness = 1;
            this.addButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addButton.OnDisabledState.IconLeftImage = null;
            this.addButton.OnDisabledState.IconRightImage = null;
            this.addButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.onHoverState.BorderRadius = 1;
            this.addButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.onHoverState.BorderThickness = 1;
            this.addButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addButton.onHoverState.IconLeftImage = null;
            this.addButton.onHoverState.IconRightImage = null;
            this.addButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnIdleState.BorderRadius = 1;
            this.addButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnIdleState.BorderThickness = 1;
            this.addButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.addButton.OnIdleState.IconLeftImage = null;
            this.addButton.OnIdleState.IconRightImage = null;
            this.addButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnPressedState.BorderRadius = 1;
            this.addButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnPressedState.BorderThickness = 1;
            this.addButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addButton.OnPressedState.IconLeftImage = null;
            this.addButton.OnPressedState.IconRightImage = null;
            this.addButton.Size = new System.Drawing.Size(75, 40);
            this.addButton.TabIndex = 50;
            this.addButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addButton.TextMarginLeft = 0;
            this.addButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.addButton.UseDefaultRadiusAndThickness = true;
            this.addButton.Click += new System.EventHandler(this.addButton_Click);
            // 
            // drugsGridView
            // 
            this.drugsGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.drugsGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.drugsGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.drugsGridView.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.drugsGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.drugsGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.drugsGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.drugsGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.drugsGridView.ColumnHeadersHeight = 40;
            this.drugsGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.drugsGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.drugsGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.drugsGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.drugsGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.drugsGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.drugsGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.drugsGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.drugsGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.drugsGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.drugsGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.drugsGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.drugsGridView.CurrentTheme.Name = null;
            this.drugsGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.drugsGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.drugsGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.drugsGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.drugsGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.drugsGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.drugsGridView.EnableHeadersVisualStyles = false;
            this.drugsGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.drugsGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.drugsGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.drugsGridView.HeaderForeColor = System.Drawing.Color.White;
            this.drugsGridView.Location = new System.Drawing.Point(12, 319);
            this.drugsGridView.Name = "drugsGridView";
            this.drugsGridView.RowHeadersVisible = false;
            this.drugsGridView.RowHeadersWidth = 51;
            this.drugsGridView.RowTemplate.Height = 40;
            this.drugsGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.drugsGridView.Size = new System.Drawing.Size(758, 222);
            this.drugsGridView.TabIndex = 49;
            this.drugsGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // quantityTextbox
            // 
            this.quantityTextbox.AcceptsReturn = false;
            this.quantityTextbox.AcceptsTab = false;
            this.quantityTextbox.AnimationSpeed = 200;
            this.quantityTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.quantityTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.quantityTextbox.BackColor = System.Drawing.Color.Transparent;
            this.quantityTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("quantityTextbox.BackgroundImage")));
            this.quantityTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.quantityTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.quantityTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.quantityTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.quantityTextbox.BorderRadius = 1;
            this.quantityTextbox.BorderThickness = 1;
            this.quantityTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.quantityTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.quantityTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.quantityTextbox.DefaultText = "";
            this.quantityTextbox.FillColor = System.Drawing.Color.White;
            this.quantityTextbox.HideSelection = true;
            this.quantityTextbox.IconLeft = null;
            this.quantityTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.quantityTextbox.IconPadding = 10;
            this.quantityTextbox.IconRight = null;
            this.quantityTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.quantityTextbox.Lines = new string[0];
            this.quantityTextbox.Location = new System.Drawing.Point(350, 143);
            this.quantityTextbox.MaxLength = 32767;
            this.quantityTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.quantityTextbox.Modified = false;
            this.quantityTextbox.Multiline = false;
            this.quantityTextbox.Name = "quantityTextbox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quantityTextbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.quantityTextbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quantityTextbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quantityTextbox.OnIdleState = stateProperties4;
            this.quantityTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.quantityTextbox.PasswordChar = '\0';
            this.quantityTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.quantityTextbox.PlaceholderText = "Enter text";
            this.quantityTextbox.ReadOnly = false;
            this.quantityTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.quantityTextbox.SelectedText = "";
            this.quantityTextbox.SelectionLength = 0;
            this.quantityTextbox.SelectionStart = 0;
            this.quantityTextbox.ShortcutsEnabled = true;
            this.quantityTextbox.Size = new System.Drawing.Size(294, 28);
            this.quantityTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.quantityTextbox.TabIndex = 47;
            this.quantityTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.quantityTextbox.TextMarginBottom = 0;
            this.quantityTextbox.TextMarginLeft = 3;
            this.quantityTextbox.TextMarginTop = 0;
            this.quantityTextbox.TextPlaceholder = "Enter text";
            this.quantityTextbox.UseSystemPasswordChar = false;
            this.quantityTextbox.WordWrap = true;
            // 
            // nameTextbox
            // 
            this.nameTextbox.AcceptsReturn = false;
            this.nameTextbox.AcceptsTab = false;
            this.nameTextbox.AnimationSpeed = 200;
            this.nameTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameTextbox.BackColor = System.Drawing.Color.Transparent;
            this.nameTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameTextbox.BackgroundImage")));
            this.nameTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameTextbox.BorderRadius = 1;
            this.nameTextbox.BorderThickness = 1;
            this.nameTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameTextbox.DefaultText = "";
            this.nameTextbox.FillColor = System.Drawing.Color.White;
            this.nameTextbox.HideSelection = true;
            this.nameTextbox.IconLeft = null;
            this.nameTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextbox.IconPadding = 10;
            this.nameTextbox.IconRight = null;
            this.nameTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextbox.Lines = new string[0];
            this.nameTextbox.Location = new System.Drawing.Point(350, 101);
            this.nameTextbox.MaxLength = 32767;
            this.nameTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameTextbox.Modified = false;
            this.nameTextbox.Multiline = false;
            this.nameTextbox.Name = "nameTextbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameTextbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextbox.OnIdleState = stateProperties8;
            this.nameTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.nameTextbox.PasswordChar = '\0';
            this.nameTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameTextbox.PlaceholderText = "Enter text";
            this.nameTextbox.ReadOnly = false;
            this.nameTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameTextbox.SelectedText = "";
            this.nameTextbox.SelectionLength = 0;
            this.nameTextbox.SelectionStart = 0;
            this.nameTextbox.ShortcutsEnabled = true;
            this.nameTextbox.Size = new System.Drawing.Size(294, 28);
            this.nameTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nameTextbox.TabIndex = 46;
            this.nameTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameTextbox.TextMarginBottom = 0;
            this.nameTextbox.TextMarginLeft = 3;
            this.nameTextbox.TextMarginTop = 0;
            this.nameTextbox.TextPlaceholder = "Enter text";
            this.nameTextbox.UseSystemPasswordChar = false;
            this.nameTextbox.WordWrap = true;
            // 
            // drugIdTextbox
            // 
            this.drugIdTextbox.AcceptsReturn = false;
            this.drugIdTextbox.AcceptsTab = false;
            this.drugIdTextbox.AnimationSpeed = 200;
            this.drugIdTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.drugIdTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.drugIdTextbox.BackColor = System.Drawing.Color.Transparent;
            this.drugIdTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("drugIdTextbox.BackgroundImage")));
            this.drugIdTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.drugIdTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drugIdTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.drugIdTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.drugIdTextbox.BorderRadius = 1;
            this.drugIdTextbox.BorderThickness = 1;
            this.drugIdTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.drugIdTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.drugIdTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.drugIdTextbox.DefaultText = "";
            this.drugIdTextbox.FillColor = System.Drawing.Color.White;
            this.drugIdTextbox.HideSelection = true;
            this.drugIdTextbox.IconLeft = null;
            this.drugIdTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.drugIdTextbox.IconPadding = 10;
            this.drugIdTextbox.IconRight = null;
            this.drugIdTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.drugIdTextbox.Lines = new string[0];
            this.drugIdTextbox.Location = new System.Drawing.Point(350, 61);
            this.drugIdTextbox.MaxLength = 32767;
            this.drugIdTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.drugIdTextbox.Modified = false;
            this.drugIdTextbox.Multiline = false;
            this.drugIdTextbox.Name = "drugIdTextbox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.drugIdTextbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.drugIdTextbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.drugIdTextbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.drugIdTextbox.OnIdleState = stateProperties12;
            this.drugIdTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.drugIdTextbox.PasswordChar = '\0';
            this.drugIdTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.drugIdTextbox.PlaceholderText = "Enter text";
            this.drugIdTextbox.ReadOnly = false;
            this.drugIdTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.drugIdTextbox.SelectedText = "";
            this.drugIdTextbox.SelectionLength = 0;
            this.drugIdTextbox.SelectionStart = 0;
            this.drugIdTextbox.ShortcutsEnabled = true;
            this.drugIdTextbox.Size = new System.Drawing.Size(294, 28);
            this.drugIdTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.drugIdTextbox.TabIndex = 45;
            this.drugIdTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.drugIdTextbox.TextMarginBottom = 0;
            this.drugIdTextbox.TextMarginLeft = 3;
            this.drugIdTextbox.TextMarginTop = 0;
            this.drugIdTextbox.TextPlaceholder = "Enter text";
            this.drugIdTextbox.UseSystemPasswordChar = false;
            this.drugIdTextbox.WordWrap = true;
            // 
            // dosageLabel
            // 
            this.dosageLabel.AutoSize = true;
            this.dosageLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dosageLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.dosageLabel.Location = new System.Drawing.Point(151, 189);
            this.dosageLabel.Name = "dosageLabel";
            this.dosageLabel.Size = new System.Drawing.Size(86, 25);
            this.dosageLabel.TabIndex = 44;
            this.dosageLabel.Text = "Dosage";
            // 
            // quantityLabel
            // 
            this.quantityLabel.AutoSize = true;
            this.quantityLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.quantityLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.quantityLabel.Location = new System.Drawing.Point(151, 146);
            this.quantityLabel.Name = "quantityLabel";
            this.quantityLabel.Size = new System.Drawing.Size(92, 25);
            this.quantityLabel.TabIndex = 43;
            this.quantityLabel.Text = "Quantity";
            // 
            // nameLabel
            // 
            this.nameLabel.AutoSize = true;
            this.nameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nameLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.nameLabel.Location = new System.Drawing.Point(151, 101);
            this.nameLabel.Name = "nameLabel";
            this.nameLabel.Size = new System.Drawing.Size(68, 25);
            this.nameLabel.TabIndex = 42;
            this.nameLabel.Text = "Name";
            // 
            // drugIdLabel
            // 
            this.drugIdLabel.AutoSize = true;
            this.drugIdLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drugIdLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.drugIdLabel.Location = new System.Drawing.Point(151, 61);
            this.drugIdLabel.Name = "drugIdLabel";
            this.drugIdLabel.Size = new System.Drawing.Size(84, 25);
            this.drugIdLabel.TabIndex = 41;
            this.drugIdLabel.Text = "Drug ID";
            // 
            // backButton
            // 
            this.backButton.AllowAnimations = true;
            this.backButton.AllowMouseEffects = true;
            this.backButton.AllowToggling = false;
            this.backButton.AnimationSpeed = 200;
            this.backButton.AutoGenerateColors = false;
            this.backButton.AutoRoundBorders = false;
            this.backButton.AutoSizeLeftIcon = true;
            this.backButton.AutoSizeRightIcon = true;
            this.backButton.BackColor = System.Drawing.Color.Transparent;
            this.backButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("backButton.BackgroundImage")));
            this.backButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.ButtonText = "Back";
            this.backButton.ButtonTextMarginLeft = 0;
            this.backButton.ColorContrastOnClick = 45;
            this.backButton.ColorContrastOnHover = 45;
            this.backButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.backButton.CustomizableEdges = borderEdges5;
            this.backButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.backButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.backButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.backButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.backButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.backButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.backButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.backButton.IconMarginLeft = 11;
            this.backButton.IconPadding = 10;
            this.backButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.backButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.backButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.backButton.IconSize = 25;
            this.backButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.IdleBorderRadius = 1;
            this.backButton.IdleBorderThickness = 1;
            this.backButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.IdleIconLeftImage = null;
            this.backButton.IdleIconRightImage = null;
            this.backButton.IndicateFocus = false;
            this.backButton.Location = new System.Drawing.Point(12, 12);
            this.backButton.Name = "backButton";
            this.backButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backButton.OnDisabledState.BorderRadius = 1;
            this.backButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnDisabledState.BorderThickness = 1;
            this.backButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backButton.OnDisabledState.IconLeftImage = null;
            this.backButton.OnDisabledState.IconRightImage = null;
            this.backButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.onHoverState.BorderRadius = 1;
            this.backButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.onHoverState.BorderThickness = 1;
            this.backButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.backButton.onHoverState.IconLeftImage = null;
            this.backButton.onHoverState.IconRightImage = null;
            this.backButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnIdleState.BorderRadius = 1;
            this.backButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnIdleState.BorderThickness = 1;
            this.backButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.backButton.OnIdleState.IconLeftImage = null;
            this.backButton.OnIdleState.IconRightImage = null;
            this.backButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnPressedState.BorderRadius = 1;
            this.backButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnPressedState.BorderThickness = 1;
            this.backButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.backButton.OnPressedState.IconLeftImage = null;
            this.backButton.OnPressedState.IconRightImage = null;
            this.backButton.Size = new System.Drawing.Size(75, 40);
            this.backButton.TabIndex = 40;
            this.backButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.backButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.backButton.TextMarginLeft = 0;
            this.backButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.backButton.UseDefaultRadiusAndThickness = true;
            this.backButton.Click += new System.EventHandler(this.backButton_Click);
            // 
            // dosageTextbox
            // 
            this.dosageTextbox.AcceptsReturn = false;
            this.dosageTextbox.AcceptsTab = false;
            this.dosageTextbox.AnimationSpeed = 200;
            this.dosageTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.dosageTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.dosageTextbox.BackColor = System.Drawing.Color.Transparent;
            this.dosageTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("dosageTextbox.BackgroundImage")));
            this.dosageTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.dosageTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dosageTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.dosageTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.dosageTextbox.BorderRadius = 1;
            this.dosageTextbox.BorderThickness = 1;
            this.dosageTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.dosageTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.dosageTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.dosageTextbox.DefaultText = "";
            this.dosageTextbox.FillColor = System.Drawing.Color.White;
            this.dosageTextbox.HideSelection = true;
            this.dosageTextbox.IconLeft = null;
            this.dosageTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.dosageTextbox.IconPadding = 10;
            this.dosageTextbox.IconRight = null;
            this.dosageTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.dosageTextbox.Lines = new string[0];
            this.dosageTextbox.Location = new System.Drawing.Point(350, 186);
            this.dosageTextbox.MaxLength = 32767;
            this.dosageTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.dosageTextbox.Modified = false;
            this.dosageTextbox.Multiline = false;
            this.dosageTextbox.Name = "dosageTextbox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dosageTextbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.dosageTextbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dosageTextbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.dosageTextbox.OnIdleState = stateProperties16;
            this.dosageTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.dosageTextbox.PasswordChar = '\0';
            this.dosageTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.dosageTextbox.PlaceholderText = "Enter text";
            this.dosageTextbox.ReadOnly = false;
            this.dosageTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dosageTextbox.SelectedText = "";
            this.dosageTextbox.SelectionLength = 0;
            this.dosageTextbox.SelectionStart = 0;
            this.dosageTextbox.ShortcutsEnabled = true;
            this.dosageTextbox.Size = new System.Drawing.Size(294, 28);
            this.dosageTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.dosageTextbox.TabIndex = 54;
            this.dosageTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.dosageTextbox.TextMarginBottom = 0;
            this.dosageTextbox.TextMarginLeft = 3;
            this.dosageTextbox.TextMarginTop = 0;
            this.dosageTextbox.TextPlaceholder = "Enter text";
            this.dosageTextbox.UseSystemPasswordChar = false;
            this.dosageTextbox.WordWrap = true;
            // 
            // prescriptionIdLabel
            // 
            this.prescriptionIdLabel.AutoSize = true;
            this.prescriptionIdLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.prescriptionIdLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.prescriptionIdLabel.Location = new System.Drawing.Point(151, 226);
            this.prescriptionIdLabel.Name = "prescriptionIdLabel";
            this.prescriptionIdLabel.Size = new System.Drawing.Size(152, 25);
            this.prescriptionIdLabel.TabIndex = 55;
            this.prescriptionIdLabel.Text = "Prescription ID";
            // 
            // prescriptionIdTextbox
            // 
            this.prescriptionIdTextbox.AcceptsReturn = false;
            this.prescriptionIdTextbox.AcceptsTab = false;
            this.prescriptionIdTextbox.AnimationSpeed = 200;
            this.prescriptionIdTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.prescriptionIdTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.prescriptionIdTextbox.BackColor = System.Drawing.Color.Transparent;
            this.prescriptionIdTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("prescriptionIdTextbox.BackgroundImage")));
            this.prescriptionIdTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.prescriptionIdTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prescriptionIdTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.prescriptionIdTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.prescriptionIdTextbox.BorderRadius = 1;
            this.prescriptionIdTextbox.BorderThickness = 1;
            this.prescriptionIdTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.prescriptionIdTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.prescriptionIdTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.prescriptionIdTextbox.DefaultText = "";
            this.prescriptionIdTextbox.FillColor = System.Drawing.Color.White;
            this.prescriptionIdTextbox.HideSelection = true;
            this.prescriptionIdTextbox.IconLeft = null;
            this.prescriptionIdTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.prescriptionIdTextbox.IconPadding = 10;
            this.prescriptionIdTextbox.IconRight = null;
            this.prescriptionIdTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.prescriptionIdTextbox.Lines = new string[0];
            this.prescriptionIdTextbox.Location = new System.Drawing.Point(350, 226);
            this.prescriptionIdTextbox.MaxLength = 32767;
            this.prescriptionIdTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.prescriptionIdTextbox.Modified = false;
            this.prescriptionIdTextbox.Multiline = false;
            this.prescriptionIdTextbox.Name = "prescriptionIdTextbox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prescriptionIdTextbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.prescriptionIdTextbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prescriptionIdTextbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prescriptionIdTextbox.OnIdleState = stateProperties20;
            this.prescriptionIdTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.prescriptionIdTextbox.PasswordChar = '\0';
            this.prescriptionIdTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.prescriptionIdTextbox.PlaceholderText = "Enter text";
            this.prescriptionIdTextbox.ReadOnly = false;
            this.prescriptionIdTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.prescriptionIdTextbox.SelectedText = "";
            this.prescriptionIdTextbox.SelectionLength = 0;
            this.prescriptionIdTextbox.SelectionStart = 0;
            this.prescriptionIdTextbox.ShortcutsEnabled = true;
            this.prescriptionIdTextbox.Size = new System.Drawing.Size(294, 28);
            this.prescriptionIdTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.prescriptionIdTextbox.TabIndex = 56;
            this.prescriptionIdTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.prescriptionIdTextbox.TextMarginBottom = 0;
            this.prescriptionIdTextbox.TextMarginLeft = 3;
            this.prescriptionIdTextbox.TextMarginTop = 0;
            this.prescriptionIdTextbox.TextPlaceholder = "Enter text";
            this.prescriptionIdTextbox.UseSystemPasswordChar = false;
            this.prescriptionIdTextbox.WordWrap = true;
            // 
            // Drugs
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(782, 553);
            this.Controls.Add(this.prescriptionIdTextbox);
            this.Controls.Add(this.prescriptionIdLabel);
            this.Controls.Add(this.dosageTextbox);
            this.Controls.Add(this.updateButton);
            this.Controls.Add(this.reportsButton);
            this.Controls.Add(this.deleteButton);
            this.Controls.Add(this.addButton);
            this.Controls.Add(this.drugsGridView);
            this.Controls.Add(this.quantityTextbox);
            this.Controls.Add(this.nameTextbox);
            this.Controls.Add(this.drugIdTextbox);
            this.Controls.Add(this.dosageLabel);
            this.Controls.Add(this.quantityLabel);
            this.Controls.Add(this.nameLabel);
            this.Controls.Add(this.drugIdLabel);
            this.Controls.Add(this.backButton);
            this.Name = "Drugs";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MediCode";
            this.Load += new System.EventHandler(this.Drugs_Load);
            ((System.ComponentModel.ISupportInitialize)(this.drugsGridView)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton updateButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton reportsButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton deleteButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addButton;
        private Bunifu.UI.WinForms.BunifuDataGridView drugsGridView;
        private Bunifu.UI.WinForms.BunifuTextBox quantityTextbox;
        private Bunifu.UI.WinForms.BunifuTextBox nameTextbox;
        private Bunifu.UI.WinForms.BunifuTextBox drugIdTextbox;
        private System.Windows.Forms.Label dosageLabel;
        private System.Windows.Forms.Label quantityLabel;
        private System.Windows.Forms.Label nameLabel;
        private System.Windows.Forms.Label drugIdLabel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton backButton;
        private Bunifu.UI.WinForms.BunifuTextBox dosageTextbox;
        private System.Windows.Forms.Label prescriptionIdLabel;
        private Bunifu.UI.WinForms.BunifuTextBox prescriptionIdTextbox;
    }
}