
namespace MediCode
{
    partial class Patients
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Patients));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.backButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.patientIdLabel = new System.Windows.Forms.Label();
            this.lastNameLabel = new System.Windows.Forms.Label();
            this.firstNameLabel = new System.Windows.Forms.Label();
            this.birthDateLabel = new System.Windows.Forms.Label();
            this.patientIdTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lastNameTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.firstNameTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.birthDatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.patientsGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.deleteButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.reportsButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.updateButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.patientsGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // backButton
            // 
            this.backButton.AllowAnimations = true;
            this.backButton.AllowMouseEffects = true;
            this.backButton.AllowToggling = false;
            this.backButton.AnimationSpeed = 200;
            this.backButton.AutoGenerateColors = false;
            this.backButton.AutoRoundBorders = false;
            this.backButton.AutoSizeLeftIcon = true;
            this.backButton.AutoSizeRightIcon = true;
            this.backButton.BackColor = System.Drawing.Color.Transparent;
            this.backButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("backButton.BackgroundImage")));
            this.backButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.ButtonText = "Back";
            this.backButton.ButtonTextMarginLeft = 0;
            this.backButton.ColorContrastOnClick = 45;
            this.backButton.ColorContrastOnHover = 45;
            this.backButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.backButton.CustomizableEdges = borderEdges1;
            this.backButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.backButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.backButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.backButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.backButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.backButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.backButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.backButton.IconMarginLeft = 11;
            this.backButton.IconPadding = 10;
            this.backButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.backButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.backButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.backButton.IconSize = 25;
            this.backButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.IdleBorderRadius = 1;
            this.backButton.IdleBorderThickness = 1;
            this.backButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.IdleIconLeftImage = null;
            this.backButton.IdleIconRightImage = null;
            this.backButton.IndicateFocus = false;
            this.backButton.Location = new System.Drawing.Point(12, 12);
            this.backButton.Name = "backButton";
            this.backButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backButton.OnDisabledState.BorderRadius = 1;
            this.backButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnDisabledState.BorderThickness = 1;
            this.backButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backButton.OnDisabledState.IconLeftImage = null;
            this.backButton.OnDisabledState.IconRightImage = null;
            this.backButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.onHoverState.BorderRadius = 1;
            this.backButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.onHoverState.BorderThickness = 1;
            this.backButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.backButton.onHoverState.IconLeftImage = null;
            this.backButton.onHoverState.IconRightImage = null;
            this.backButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnIdleState.BorderRadius = 1;
            this.backButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnIdleState.BorderThickness = 1;
            this.backButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.backButton.OnIdleState.IconLeftImage = null;
            this.backButton.OnIdleState.IconRightImage = null;
            this.backButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnPressedState.BorderRadius = 1;
            this.backButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnPressedState.BorderThickness = 1;
            this.backButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.backButton.OnPressedState.IconLeftImage = null;
            this.backButton.OnPressedState.IconRightImage = null;
            this.backButton.Size = new System.Drawing.Size(75, 40);
            this.backButton.TabIndex = 3;
            this.backButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.backButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.backButton.TextMarginLeft = 0;
            this.backButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.backButton.UseDefaultRadiusAndThickness = true;
            this.backButton.Click += new System.EventHandler(this.backButton_Click);
            // 
            // patientIdLabel
            // 
            this.patientIdLabel.AutoSize = true;
            this.patientIdLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.patientIdLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.patientIdLabel.Location = new System.Drawing.Point(151, 61);
            this.patientIdLabel.Name = "patientIdLabel";
            this.patientIdLabel.Size = new System.Drawing.Size(105, 25);
            this.patientIdLabel.TabIndex = 8;
            this.patientIdLabel.Text = "Patient ID";
            // 
            // lastNameLabel
            // 
            this.lastNameLabel.AutoSize = true;
            this.lastNameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lastNameLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.lastNameLabel.Location = new System.Drawing.Point(151, 101);
            this.lastNameLabel.Name = "lastNameLabel";
            this.lastNameLabel.Size = new System.Drawing.Size(115, 25);
            this.lastNameLabel.TabIndex = 9;
            this.lastNameLabel.Text = "Last Name";
            // 
            // firstNameLabel
            // 
            this.firstNameLabel.AutoSize = true;
            this.firstNameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.firstNameLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.firstNameLabel.Location = new System.Drawing.Point(151, 146);
            this.firstNameLabel.Name = "firstNameLabel";
            this.firstNameLabel.Size = new System.Drawing.Size(116, 25);
            this.firstNameLabel.TabIndex = 10;
            this.firstNameLabel.Text = "First Name";
            // 
            // birthDateLabel
            // 
            this.birthDateLabel.AutoSize = true;
            this.birthDateLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.birthDateLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.birthDateLabel.Location = new System.Drawing.Point(151, 189);
            this.birthDateLabel.Name = "birthDateLabel";
            this.birthDateLabel.Size = new System.Drawing.Size(107, 25);
            this.birthDateLabel.TabIndex = 11;
            this.birthDateLabel.Text = "Birth Date";
            // 
            // patientIdTextbox
            // 
            this.patientIdTextbox.AcceptsReturn = false;
            this.patientIdTextbox.AcceptsTab = false;
            this.patientIdTextbox.AnimationSpeed = 200;
            this.patientIdTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.patientIdTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.patientIdTextbox.BackColor = System.Drawing.Color.Transparent;
            this.patientIdTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("patientIdTextbox.BackgroundImage")));
            this.patientIdTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.patientIdTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.patientIdTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.patientIdTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.patientIdTextbox.BorderRadius = 1;
            this.patientIdTextbox.BorderThickness = 1;
            this.patientIdTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.patientIdTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.patientIdTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.patientIdTextbox.DefaultText = "";
            this.patientIdTextbox.FillColor = System.Drawing.Color.White;
            this.patientIdTextbox.HideSelection = true;
            this.patientIdTextbox.IconLeft = null;
            this.patientIdTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.patientIdTextbox.IconPadding = 10;
            this.patientIdTextbox.IconRight = null;
            this.patientIdTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.patientIdTextbox.Lines = new string[0];
            this.patientIdTextbox.Location = new System.Drawing.Point(350, 61);
            this.patientIdTextbox.MaxLength = 32767;
            this.patientIdTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.patientIdTextbox.Modified = false;
            this.patientIdTextbox.Multiline = false;
            this.patientIdTextbox.Name = "patientIdTextbox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.patientIdTextbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.patientIdTextbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.patientIdTextbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.patientIdTextbox.OnIdleState = stateProperties4;
            this.patientIdTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.patientIdTextbox.PasswordChar = '\0';
            this.patientIdTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.patientIdTextbox.PlaceholderText = "Enter text";
            this.patientIdTextbox.ReadOnly = false;
            this.patientIdTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.patientIdTextbox.SelectedText = "";
            this.patientIdTextbox.SelectionLength = 0;
            this.patientIdTextbox.SelectionStart = 0;
            this.patientIdTextbox.ShortcutsEnabled = true;
            this.patientIdTextbox.Size = new System.Drawing.Size(294, 28);
            this.patientIdTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.patientIdTextbox.TabIndex = 12;
            this.patientIdTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.patientIdTextbox.TextMarginBottom = 0;
            this.patientIdTextbox.TextMarginLeft = 3;
            this.patientIdTextbox.TextMarginTop = 0;
            this.patientIdTextbox.TextPlaceholder = "Enter text";
            this.patientIdTextbox.UseSystemPasswordChar = false;
            this.patientIdTextbox.WordWrap = true;
            // 
            // lastNameTextbox
            // 
            this.lastNameTextbox.AcceptsReturn = false;
            this.lastNameTextbox.AcceptsTab = false;
            this.lastNameTextbox.AnimationSpeed = 200;
            this.lastNameTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNameTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNameTextbox.BackColor = System.Drawing.Color.Transparent;
            this.lastNameTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNameTextbox.BackgroundImage")));
            this.lastNameTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.lastNameTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastNameTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lastNameTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.lastNameTextbox.BorderRadius = 1;
            this.lastNameTextbox.BorderThickness = 1;
            this.lastNameTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNameTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lastNameTextbox.DefaultText = "";
            this.lastNameTextbox.FillColor = System.Drawing.Color.White;
            this.lastNameTextbox.HideSelection = true;
            this.lastNameTextbox.IconLeft = null;
            this.lastNameTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextbox.IconPadding = 10;
            this.lastNameTextbox.IconRight = null;
            this.lastNameTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextbox.Lines = new string[0];
            this.lastNameTextbox.Location = new System.Drawing.Point(350, 101);
            this.lastNameTextbox.MaxLength = 32767;
            this.lastNameTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastNameTextbox.Modified = false;
            this.lastNameTextbox.Multiline = false;
            this.lastNameTextbox.Name = "lastNameTextbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastNameTextbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextbox.OnIdleState = stateProperties8;
            this.lastNameTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.lastNameTextbox.PasswordChar = '\0';
            this.lastNameTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameTextbox.PlaceholderText = "Enter text";
            this.lastNameTextbox.ReadOnly = false;
            this.lastNameTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNameTextbox.SelectedText = "";
            this.lastNameTextbox.SelectionLength = 0;
            this.lastNameTextbox.SelectionStart = 0;
            this.lastNameTextbox.ShortcutsEnabled = true;
            this.lastNameTextbox.Size = new System.Drawing.Size(294, 28);
            this.lastNameTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastNameTextbox.TabIndex = 13;
            this.lastNameTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNameTextbox.TextMarginBottom = 0;
            this.lastNameTextbox.TextMarginLeft = 3;
            this.lastNameTextbox.TextMarginTop = 0;
            this.lastNameTextbox.TextPlaceholder = "Enter text";
            this.lastNameTextbox.UseSystemPasswordChar = false;
            this.lastNameTextbox.WordWrap = true;
            // 
            // firstNameTextbox
            // 
            this.firstNameTextbox.AcceptsReturn = false;
            this.firstNameTextbox.AcceptsTab = false;
            this.firstNameTextbox.AnimationSpeed = 200;
            this.firstNameTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstNameTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstNameTextbox.BackColor = System.Drawing.Color.Transparent;
            this.firstNameTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstNameTextbox.BackgroundImage")));
            this.firstNameTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.firstNameTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.firstNameTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.firstNameTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.firstNameTextbox.BorderRadius = 1;
            this.firstNameTextbox.BorderThickness = 1;
            this.firstNameTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstNameTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.firstNameTextbox.DefaultText = "";
            this.firstNameTextbox.FillColor = System.Drawing.Color.White;
            this.firstNameTextbox.HideSelection = true;
            this.firstNameTextbox.IconLeft = null;
            this.firstNameTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTextbox.IconPadding = 10;
            this.firstNameTextbox.IconRight = null;
            this.firstNameTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTextbox.Lines = new string[0];
            this.firstNameTextbox.Location = new System.Drawing.Point(350, 146);
            this.firstNameTextbox.MaxLength = 32767;
            this.firstNameTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.firstNameTextbox.Modified = false;
            this.firstNameTextbox.Multiline = false;
            this.firstNameTextbox.Name = "firstNameTextbox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTextbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.firstNameTextbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTextbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTextbox.OnIdleState = stateProperties12;
            this.firstNameTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.firstNameTextbox.PasswordChar = '\0';
            this.firstNameTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNameTextbox.PlaceholderText = "Enter text";
            this.firstNameTextbox.ReadOnly = false;
            this.firstNameTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstNameTextbox.SelectedText = "";
            this.firstNameTextbox.SelectionLength = 0;
            this.firstNameTextbox.SelectionStart = 0;
            this.firstNameTextbox.ShortcutsEnabled = true;
            this.firstNameTextbox.Size = new System.Drawing.Size(294, 28);
            this.firstNameTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.firstNameTextbox.TabIndex = 14;
            this.firstNameTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstNameTextbox.TextMarginBottom = 0;
            this.firstNameTextbox.TextMarginLeft = 3;
            this.firstNameTextbox.TextMarginTop = 0;
            this.firstNameTextbox.TextPlaceholder = "Enter text";
            this.firstNameTextbox.UseSystemPasswordChar = false;
            this.firstNameTextbox.WordWrap = true;
            // 
            // birthDatePicker
            // 
            this.birthDatePicker.BackColor = System.Drawing.Color.Transparent;
            this.birthDatePicker.BorderRadius = 1;
            this.birthDatePicker.Color = System.Drawing.Color.Silver;
            this.birthDatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.birthDatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.birthDatePicker.DisabledColor = System.Drawing.Color.Gray;
            this.birthDatePicker.DisplayWeekNumbers = false;
            this.birthDatePicker.DPHeight = 0;
            this.birthDatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.birthDatePicker.FillDatePicker = false;
            this.birthDatePicker.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.birthDatePicker.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.birthDatePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.birthDatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("birthDatePicker.Icon")));
            this.birthDatePicker.IconColor = System.Drawing.Color.Gray;
            this.birthDatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.birthDatePicker.LeftTextMargin = 5;
            this.birthDatePicker.Location = new System.Drawing.Point(350, 189);
            this.birthDatePicker.MinimumSize = new System.Drawing.Size(4, 32);
            this.birthDatePicker.Name = "birthDatePicker";
            this.birthDatePicker.Size = new System.Drawing.Size(294, 32);
            this.birthDatePicker.TabIndex = 15;
            // 
            // patientsGridView
            // 
            this.patientsGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.patientsGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.patientsGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.patientsGridView.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.patientsGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.patientsGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.patientsGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.patientsGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.patientsGridView.ColumnHeadersHeight = 40;
            this.patientsGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.patientsGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.patientsGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.patientsGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.patientsGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.patientsGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.patientsGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.patientsGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.patientsGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.patientsGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.patientsGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.patientsGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.patientsGridView.CurrentTheme.Name = null;
            this.patientsGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.patientsGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.patientsGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.patientsGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.patientsGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.patientsGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.patientsGridView.EnableHeadersVisualStyles = false;
            this.patientsGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.patientsGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.patientsGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.patientsGridView.HeaderForeColor = System.Drawing.Color.White;
            this.patientsGridView.Location = new System.Drawing.Point(12, 292);
            this.patientsGridView.Name = "patientsGridView";
            this.patientsGridView.RowHeadersVisible = false;
            this.patientsGridView.RowHeadersWidth = 51;
            this.patientsGridView.RowTemplate.Height = 40;
            this.patientsGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.patientsGridView.Size = new System.Drawing.Size(758, 249);
            this.patientsGridView.TabIndex = 16;
            this.patientsGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // deleteButton
            // 
            this.deleteButton.AllowAnimations = true;
            this.deleteButton.AllowMouseEffects = true;
            this.deleteButton.AllowToggling = false;
            this.deleteButton.AnimationSpeed = 200;
            this.deleteButton.AutoGenerateColors = false;
            this.deleteButton.AutoRoundBorders = false;
            this.deleteButton.AutoSizeLeftIcon = true;
            this.deleteButton.AutoSizeRightIcon = true;
            this.deleteButton.BackColor = System.Drawing.Color.Transparent;
            this.deleteButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteButton.BackgroundImage")));
            this.deleteButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.ButtonText = "Delete";
            this.deleteButton.ButtonTextMarginLeft = 0;
            this.deleteButton.ColorContrastOnClick = 45;
            this.deleteButton.ColorContrastOnHover = 45;
            this.deleteButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.deleteButton.CustomizableEdges = borderEdges2;
            this.deleteButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deleteButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.deleteButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.deleteButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.deleteButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deleteButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deleteButton.IconMarginLeft = 11;
            this.deleteButton.IconPadding = 10;
            this.deleteButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deleteButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deleteButton.IconSize = 25;
            this.deleteButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.IdleBorderRadius = 1;
            this.deleteButton.IdleBorderThickness = 1;
            this.deleteButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.IdleIconLeftImage = null;
            this.deleteButton.IdleIconRightImage = null;
            this.deleteButton.IndicateFocus = false;
            this.deleteButton.Location = new System.Drawing.Point(569, 239);
            this.deleteButton.Name = "deleteButton";
            this.deleteButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteButton.OnDisabledState.BorderRadius = 1;
            this.deleteButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnDisabledState.BorderThickness = 1;
            this.deleteButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteButton.OnDisabledState.IconLeftImage = null;
            this.deleteButton.OnDisabledState.IconRightImage = null;
            this.deleteButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.onHoverState.BorderRadius = 1;
            this.deleteButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.onHoverState.BorderThickness = 1;
            this.deleteButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deleteButton.onHoverState.IconLeftImage = null;
            this.deleteButton.onHoverState.IconRightImage = null;
            this.deleteButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnIdleState.BorderRadius = 1;
            this.deleteButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnIdleState.BorderThickness = 1;
            this.deleteButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.deleteButton.OnIdleState.IconLeftImage = null;
            this.deleteButton.OnIdleState.IconRightImage = null;
            this.deleteButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnPressedState.BorderRadius = 1;
            this.deleteButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnPressedState.BorderThickness = 1;
            this.deleteButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deleteButton.OnPressedState.IconLeftImage = null;
            this.deleteButton.OnPressedState.IconRightImage = null;
            this.deleteButton.Size = new System.Drawing.Size(75, 40);
            this.deleteButton.TabIndex = 37;
            this.deleteButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.deleteButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deleteButton.TextMarginLeft = 0;
            this.deleteButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.deleteButton.UseDefaultRadiusAndThickness = true;
            this.deleteButton.Click += new System.EventHandler(this.deleteButton_Click);
            // 
            // addButton
            // 
            this.addButton.AllowAnimations = true;
            this.addButton.AllowMouseEffects = true;
            this.addButton.AllowToggling = false;
            this.addButton.AnimationSpeed = 200;
            this.addButton.AutoGenerateColors = false;
            this.addButton.AutoRoundBorders = false;
            this.addButton.AutoSizeLeftIcon = true;
            this.addButton.AutoSizeRightIcon = true;
            this.addButton.BackColor = System.Drawing.Color.Transparent;
            this.addButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addButton.BackgroundImage")));
            this.addButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.ButtonText = "Add";
            this.addButton.ButtonTextMarginLeft = 0;
            this.addButton.ColorContrastOnClick = 45;
            this.addButton.ColorContrastOnHover = 45;
            this.addButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.addButton.CustomizableEdges = borderEdges3;
            this.addButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.addButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.addButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addButton.IconMarginLeft = 11;
            this.addButton.IconPadding = 10;
            this.addButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addButton.IconSize = 25;
            this.addButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.IdleBorderRadius = 1;
            this.addButton.IdleBorderThickness = 1;
            this.addButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.IdleIconLeftImage = null;
            this.addButton.IdleIconRightImage = null;
            this.addButton.IndicateFocus = false;
            this.addButton.Location = new System.Drawing.Point(350, 239);
            this.addButton.Name = "addButton";
            this.addButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addButton.OnDisabledState.BorderRadius = 1;
            this.addButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnDisabledState.BorderThickness = 1;
            this.addButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addButton.OnDisabledState.IconLeftImage = null;
            this.addButton.OnDisabledState.IconRightImage = null;
            this.addButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.onHoverState.BorderRadius = 1;
            this.addButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.onHoverState.BorderThickness = 1;
            this.addButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addButton.onHoverState.IconLeftImage = null;
            this.addButton.onHoverState.IconRightImage = null;
            this.addButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnIdleState.BorderRadius = 1;
            this.addButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnIdleState.BorderThickness = 1;
            this.addButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.addButton.OnIdleState.IconLeftImage = null;
            this.addButton.OnIdleState.IconRightImage = null;
            this.addButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnPressedState.BorderRadius = 1;
            this.addButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnPressedState.BorderThickness = 1;
            this.addButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addButton.OnPressedState.IconLeftImage = null;
            this.addButton.OnPressedState.IconRightImage = null;
            this.addButton.Size = new System.Drawing.Size(75, 40);
            this.addButton.TabIndex = 35;
            this.addButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addButton.TextMarginLeft = 0;
            this.addButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.addButton.UseDefaultRadiusAndThickness = true;
            this.addButton.Click += new System.EventHandler(this.addButton_Click);
            // 
            // reportsButton
            // 
            this.reportsButton.AllowAnimations = true;
            this.reportsButton.AllowMouseEffects = true;
            this.reportsButton.AllowToggling = false;
            this.reportsButton.AnimationSpeed = 200;
            this.reportsButton.AutoGenerateColors = false;
            this.reportsButton.AutoRoundBorders = false;
            this.reportsButton.AutoSizeLeftIcon = true;
            this.reportsButton.AutoSizeRightIcon = true;
            this.reportsButton.BackColor = System.Drawing.Color.Transparent;
            this.reportsButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.reportsButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("reportsButton.BackgroundImage")));
            this.reportsButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.ButtonText = "Reports";
            this.reportsButton.ButtonTextMarginLeft = 0;
            this.reportsButton.ColorContrastOnClick = 45;
            this.reportsButton.ColorContrastOnHover = 45;
            this.reportsButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.reportsButton.CustomizableEdges = borderEdges4;
            this.reportsButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.reportsButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportsButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportsButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportsButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.reportsButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.reportsButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.reportsButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.reportsButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.reportsButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.reportsButton.IconMarginLeft = 11;
            this.reportsButton.IconPadding = 10;
            this.reportsButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.reportsButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.reportsButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.reportsButton.IconSize = 25;
            this.reportsButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.IdleBorderRadius = 1;
            this.reportsButton.IdleBorderThickness = 1;
            this.reportsButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.reportsButton.IdleIconLeftImage = null;
            this.reportsButton.IdleIconRightImage = null;
            this.reportsButton.IndicateFocus = false;
            this.reportsButton.Location = new System.Drawing.Point(695, 12);
            this.reportsButton.Name = "reportsButton";
            this.reportsButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportsButton.OnDisabledState.BorderRadius = 1;
            this.reportsButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.OnDisabledState.BorderThickness = 1;
            this.reportsButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportsButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportsButton.OnDisabledState.IconLeftImage = null;
            this.reportsButton.OnDisabledState.IconRightImage = null;
            this.reportsButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.onHoverState.BorderRadius = 1;
            this.reportsButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.onHoverState.BorderThickness = 1;
            this.reportsButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.reportsButton.onHoverState.IconLeftImage = null;
            this.reportsButton.onHoverState.IconRightImage = null;
            this.reportsButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.OnIdleState.BorderRadius = 1;
            this.reportsButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.OnIdleState.BorderThickness = 1;
            this.reportsButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.reportsButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.reportsButton.OnIdleState.IconLeftImage = null;
            this.reportsButton.OnIdleState.IconRightImage = null;
            this.reportsButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.OnPressedState.BorderRadius = 1;
            this.reportsButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportsButton.OnPressedState.BorderThickness = 1;
            this.reportsButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.reportsButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.reportsButton.OnPressedState.IconLeftImage = null;
            this.reportsButton.OnPressedState.IconRightImage = null;
            this.reportsButton.Size = new System.Drawing.Size(75, 40);
            this.reportsButton.TabIndex = 38;
            this.reportsButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.reportsButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.reportsButton.TextMarginLeft = 0;
            this.reportsButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.reportsButton.UseDefaultRadiusAndThickness = true;
            this.reportsButton.Click += new System.EventHandler(this.reportsButton_Click);
            // 
            // updateButton
            // 
            this.updateButton.AllowAnimations = true;
            this.updateButton.AllowMouseEffects = true;
            this.updateButton.AllowToggling = false;
            this.updateButton.AnimationSpeed = 200;
            this.updateButton.AutoGenerateColors = false;
            this.updateButton.AutoRoundBorders = false;
            this.updateButton.AutoSizeLeftIcon = true;
            this.updateButton.AutoSizeRightIcon = true;
            this.updateButton.BackColor = System.Drawing.Color.Transparent;
            this.updateButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("updateButton.BackgroundImage")));
            this.updateButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.ButtonText = "Update";
            this.updateButton.ButtonTextMarginLeft = 0;
            this.updateButton.ColorContrastOnClick = 45;
            this.updateButton.ColorContrastOnHover = 45;
            this.updateButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.updateButton.CustomizableEdges = borderEdges5;
            this.updateButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.updateButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.updateButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.updateButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.updateButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.updateButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.updateButton.IconMarginLeft = 11;
            this.updateButton.IconPadding = 10;
            this.updateButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.updateButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.updateButton.IconSize = 25;
            this.updateButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.IdleBorderRadius = 1;
            this.updateButton.IdleBorderThickness = 1;
            this.updateButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.IdleIconLeftImage = null;
            this.updateButton.IdleIconRightImage = null;
            this.updateButton.IndicateFocus = false;
            this.updateButton.Location = new System.Drawing.Point(460, 239);
            this.updateButton.Name = "updateButton";
            this.updateButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.OnDisabledState.BorderRadius = 1;
            this.updateButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnDisabledState.BorderThickness = 1;
            this.updateButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.OnDisabledState.IconLeftImage = null;
            this.updateButton.OnDisabledState.IconRightImage = null;
            this.updateButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.onHoverState.BorderRadius = 1;
            this.updateButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.onHoverState.BorderThickness = 1;
            this.updateButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.updateButton.onHoverState.IconLeftImage = null;
            this.updateButton.onHoverState.IconRightImage = null;
            this.updateButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnIdleState.BorderRadius = 1;
            this.updateButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnIdleState.BorderThickness = 1;
            this.updateButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.updateButton.OnIdleState.IconLeftImage = null;
            this.updateButton.OnIdleState.IconRightImage = null;
            this.updateButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.BorderRadius = 1;
            this.updateButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnPressedState.BorderThickness = 1;
            this.updateButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.updateButton.OnPressedState.IconLeftImage = null;
            this.updateButton.OnPressedState.IconRightImage = null;
            this.updateButton.Size = new System.Drawing.Size(75, 40);
            this.updateButton.TabIndex = 39;
            this.updateButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.updateButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.updateButton.TextMarginLeft = 0;
            this.updateButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.updateButton.UseDefaultRadiusAndThickness = true;
            this.updateButton.Click += new System.EventHandler(this.updateButton_Click);
            // 
            // Patients
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(782, 553);
            this.Controls.Add(this.updateButton);
            this.Controls.Add(this.reportsButton);
            this.Controls.Add(this.deleteButton);
            this.Controls.Add(this.addButton);
            this.Controls.Add(this.patientsGridView);
            this.Controls.Add(this.birthDatePicker);
            this.Controls.Add(this.firstNameTextbox);
            this.Controls.Add(this.lastNameTextbox);
            this.Controls.Add(this.patientIdTextbox);
            this.Controls.Add(this.birthDateLabel);
            this.Controls.Add(this.firstNameLabel);
            this.Controls.Add(this.lastNameLabel);
            this.Controls.Add(this.patientIdLabel);
            this.Controls.Add(this.backButton);
            this.Name = "Patients";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MediCode";
            this.Load += new System.EventHandler(this.Patients_Load);
            ((System.ComponentModel.ISupportInitialize)(this.patientsGridView)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton backButton;
        private System.Windows.Forms.Label patientIdLabel;
        private System.Windows.Forms.Label lastNameLabel;
        private System.Windows.Forms.Label firstNameLabel;
        private System.Windows.Forms.Label birthDateLabel;
        private Bunifu.UI.WinForms.BunifuTextBox patientIdTextbox;
        private Bunifu.UI.WinForms.BunifuTextBox lastNameTextbox;
        private Bunifu.UI.WinForms.BunifuTextBox firstNameTextbox;
        private Bunifu.UI.WinForms.BunifuDatePicker birthDatePicker;
        private Bunifu.UI.WinForms.BunifuDataGridView patientsGridView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton deleteButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton reportsButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton updateButton;
    }
}