
namespace MediCode
{
    partial class Prescriptions
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Prescriptions));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.prescriptionsGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.issueDatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.numberTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.seriesTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.prescriptionIdTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.issueDateLabel = new System.Windows.Forms.Label();
            this.numberLabel = new System.Windows.Forms.Label();
            this.seriesLabel = new System.Windows.Forms.Label();
            this.prescriptionIdLabel = new System.Windows.Forms.Label();
            this.deleteButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.updateButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.backButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.patientIdLabel = new System.Windows.Forms.Label();
            this.patientIdTextbox = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.prescriptionsGridView)).BeginInit();
            this.SuspendLayout();
            // 
            // prescriptionsGridView
            // 
            this.prescriptionsGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.prescriptionsGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.prescriptionsGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.prescriptionsGridView.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.prescriptionsGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.prescriptionsGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.prescriptionsGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.prescriptionsGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.prescriptionsGridView.ColumnHeadersHeight = 40;
            this.prescriptionsGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.prescriptionsGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.prescriptionsGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.prescriptionsGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.prescriptionsGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.prescriptionsGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.prescriptionsGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.prescriptionsGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.prescriptionsGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.prescriptionsGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.prescriptionsGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.prescriptionsGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.prescriptionsGridView.CurrentTheme.Name = null;
            this.prescriptionsGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.prescriptionsGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.prescriptionsGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.prescriptionsGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.prescriptionsGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.prescriptionsGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.prescriptionsGridView.EnableHeadersVisualStyles = false;
            this.prescriptionsGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.prescriptionsGridView.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.prescriptionsGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.prescriptionsGridView.HeaderForeColor = System.Drawing.Color.White;
            this.prescriptionsGridView.Location = new System.Drawing.Point(12, 334);
            this.prescriptionsGridView.Name = "prescriptionsGridView";
            this.prescriptionsGridView.RowHeadersVisible = false;
            this.prescriptionsGridView.RowHeadersWidth = 51;
            this.prescriptionsGridView.RowTemplate.Height = 40;
            this.prescriptionsGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.prescriptionsGridView.Size = new System.Drawing.Size(758, 207);
            this.prescriptionsGridView.TabIndex = 30;
            this.prescriptionsGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // issueDatePicker
            // 
            this.issueDatePicker.BackColor = System.Drawing.Color.Transparent;
            this.issueDatePicker.BorderRadius = 1;
            this.issueDatePicker.Color = System.Drawing.Color.Silver;
            this.issueDatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.issueDatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.issueDatePicker.DisabledColor = System.Drawing.Color.Gray;
            this.issueDatePicker.DisplayWeekNumbers = false;
            this.issueDatePicker.DPHeight = 0;
            this.issueDatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.issueDatePicker.FillDatePicker = false;
            this.issueDatePicker.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.issueDatePicker.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.issueDatePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.issueDatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("issueDatePicker.Icon")));
            this.issueDatePicker.IconColor = System.Drawing.Color.Gray;
            this.issueDatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.issueDatePicker.LeftTextMargin = 5;
            this.issueDatePicker.Location = new System.Drawing.Point(347, 236);
            this.issueDatePicker.MinimumSize = new System.Drawing.Size(4, 32);
            this.issueDatePicker.Name = "issueDatePicker";
            this.issueDatePicker.Size = new System.Drawing.Size(294, 32);
            this.issueDatePicker.TabIndex = 29;
            // 
            // numberTextbox
            // 
            this.numberTextbox.AcceptsReturn = false;
            this.numberTextbox.AcceptsTab = false;
            this.numberTextbox.AnimationSpeed = 200;
            this.numberTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.numberTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.numberTextbox.BackColor = System.Drawing.Color.Transparent;
            this.numberTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("numberTextbox.BackgroundImage")));
            this.numberTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.numberTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.numberTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.numberTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.numberTextbox.BorderRadius = 1;
            this.numberTextbox.BorderThickness = 1;
            this.numberTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.numberTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numberTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.numberTextbox.DefaultText = "";
            this.numberTextbox.FillColor = System.Drawing.Color.White;
            this.numberTextbox.HideSelection = true;
            this.numberTextbox.IconLeft = null;
            this.numberTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberTextbox.IconPadding = 10;
            this.numberTextbox.IconRight = null;
            this.numberTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberTextbox.Lines = new string[0];
            this.numberTextbox.Location = new System.Drawing.Point(347, 151);
            this.numberTextbox.MaxLength = 32767;
            this.numberTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.numberTextbox.Modified = false;
            this.numberTextbox.Multiline = false;
            this.numberTextbox.Name = "numberTextbox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberTextbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.numberTextbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberTextbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberTextbox.OnIdleState = stateProperties4;
            this.numberTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.numberTextbox.PasswordChar = '\0';
            this.numberTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.numberTextbox.PlaceholderText = "Enter text";
            this.numberTextbox.ReadOnly = false;
            this.numberTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numberTextbox.SelectedText = "";
            this.numberTextbox.SelectionLength = 0;
            this.numberTextbox.SelectionStart = 0;
            this.numberTextbox.ShortcutsEnabled = true;
            this.numberTextbox.Size = new System.Drawing.Size(294, 28);
            this.numberTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.numberTextbox.TabIndex = 28;
            this.numberTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.numberTextbox.TextMarginBottom = 0;
            this.numberTextbox.TextMarginLeft = 3;
            this.numberTextbox.TextMarginTop = 0;
            this.numberTextbox.TextPlaceholder = "Enter text";
            this.numberTextbox.UseSystemPasswordChar = false;
            this.numberTextbox.WordWrap = true;
            // 
            // seriesTextbox
            // 
            this.seriesTextbox.AcceptsReturn = false;
            this.seriesTextbox.AcceptsTab = false;
            this.seriesTextbox.AnimationSpeed = 200;
            this.seriesTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.seriesTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.seriesTextbox.BackColor = System.Drawing.Color.Transparent;
            this.seriesTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("seriesTextbox.BackgroundImage")));
            this.seriesTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.seriesTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.seriesTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.seriesTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.seriesTextbox.BorderRadius = 1;
            this.seriesTextbox.BorderThickness = 1;
            this.seriesTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.seriesTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.seriesTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.seriesTextbox.DefaultText = "";
            this.seriesTextbox.FillColor = System.Drawing.Color.White;
            this.seriesTextbox.HideSelection = true;
            this.seriesTextbox.IconLeft = null;
            this.seriesTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.seriesTextbox.IconPadding = 10;
            this.seriesTextbox.IconRight = null;
            this.seriesTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.seriesTextbox.Lines = new string[0];
            this.seriesTextbox.Location = new System.Drawing.Point(347, 106);
            this.seriesTextbox.MaxLength = 32767;
            this.seriesTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.seriesTextbox.Modified = false;
            this.seriesTextbox.Multiline = false;
            this.seriesTextbox.Name = "seriesTextbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.seriesTextbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.seriesTextbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.seriesTextbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.seriesTextbox.OnIdleState = stateProperties8;
            this.seriesTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.seriesTextbox.PasswordChar = '\0';
            this.seriesTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.seriesTextbox.PlaceholderText = "Enter text";
            this.seriesTextbox.ReadOnly = false;
            this.seriesTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.seriesTextbox.SelectedText = "";
            this.seriesTextbox.SelectionLength = 0;
            this.seriesTextbox.SelectionStart = 0;
            this.seriesTextbox.ShortcutsEnabled = true;
            this.seriesTextbox.Size = new System.Drawing.Size(294, 28);
            this.seriesTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.seriesTextbox.TabIndex = 27;
            this.seriesTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.seriesTextbox.TextMarginBottom = 0;
            this.seriesTextbox.TextMarginLeft = 3;
            this.seriesTextbox.TextMarginTop = 0;
            this.seriesTextbox.TextPlaceholder = "Enter text";
            this.seriesTextbox.UseSystemPasswordChar = false;
            this.seriesTextbox.WordWrap = true;
            // 
            // prescriptionIdTextbox
            // 
            this.prescriptionIdTextbox.AcceptsReturn = false;
            this.prescriptionIdTextbox.AcceptsTab = false;
            this.prescriptionIdTextbox.AnimationSpeed = 200;
            this.prescriptionIdTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.prescriptionIdTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.prescriptionIdTextbox.BackColor = System.Drawing.Color.Transparent;
            this.prescriptionIdTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("prescriptionIdTextbox.BackgroundImage")));
            this.prescriptionIdTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.prescriptionIdTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prescriptionIdTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.prescriptionIdTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.prescriptionIdTextbox.BorderRadius = 1;
            this.prescriptionIdTextbox.BorderThickness = 1;
            this.prescriptionIdTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.prescriptionIdTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.prescriptionIdTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.prescriptionIdTextbox.DefaultText = "";
            this.prescriptionIdTextbox.FillColor = System.Drawing.Color.White;
            this.prescriptionIdTextbox.HideSelection = true;
            this.prescriptionIdTextbox.IconLeft = null;
            this.prescriptionIdTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.prescriptionIdTextbox.IconPadding = 10;
            this.prescriptionIdTextbox.IconRight = null;
            this.prescriptionIdTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.prescriptionIdTextbox.Lines = new string[0];
            this.prescriptionIdTextbox.Location = new System.Drawing.Point(347, 66);
            this.prescriptionIdTextbox.MaxLength = 32767;
            this.prescriptionIdTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.prescriptionIdTextbox.Modified = false;
            this.prescriptionIdTextbox.Multiline = false;
            this.prescriptionIdTextbox.Name = "prescriptionIdTextbox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prescriptionIdTextbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.prescriptionIdTextbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prescriptionIdTextbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prescriptionIdTextbox.OnIdleState = stateProperties12;
            this.prescriptionIdTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.prescriptionIdTextbox.PasswordChar = '\0';
            this.prescriptionIdTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.prescriptionIdTextbox.PlaceholderText = "Enter text";
            this.prescriptionIdTextbox.ReadOnly = false;
            this.prescriptionIdTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.prescriptionIdTextbox.SelectedText = "";
            this.prescriptionIdTextbox.SelectionLength = 0;
            this.prescriptionIdTextbox.SelectionStart = 0;
            this.prescriptionIdTextbox.ShortcutsEnabled = true;
            this.prescriptionIdTextbox.Size = new System.Drawing.Size(294, 28);
            this.prescriptionIdTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.prescriptionIdTextbox.TabIndex = 26;
            this.prescriptionIdTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.prescriptionIdTextbox.TextMarginBottom = 0;
            this.prescriptionIdTextbox.TextMarginLeft = 3;
            this.prescriptionIdTextbox.TextMarginTop = 0;
            this.prescriptionIdTextbox.TextPlaceholder = "Enter text";
            this.prescriptionIdTextbox.UseSystemPasswordChar = false;
            this.prescriptionIdTextbox.WordWrap = true;
            // 
            // issueDateLabel
            // 
            this.issueDateLabel.AutoSize = true;
            this.issueDateLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.issueDateLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.issueDateLabel.Location = new System.Drawing.Point(145, 236);
            this.issueDateLabel.Name = "issueDateLabel";
            this.issueDateLabel.Size = new System.Drawing.Size(108, 25);
            this.issueDateLabel.TabIndex = 25;
            this.issueDateLabel.Text = "IssueDate";
            // 
            // numberLabel
            // 
            this.numberLabel.AutoSize = true;
            this.numberLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.numberLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.numberLabel.Location = new System.Drawing.Point(145, 151);
            this.numberLabel.Name = "numberLabel";
            this.numberLabel.Size = new System.Drawing.Size(87, 25);
            this.numberLabel.TabIndex = 24;
            this.numberLabel.Text = "Number";
            // 
            // seriesLabel
            // 
            this.seriesLabel.AutoSize = true;
            this.seriesLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.seriesLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.seriesLabel.Location = new System.Drawing.Point(145, 106);
            this.seriesLabel.Name = "seriesLabel";
            this.seriesLabel.Size = new System.Drawing.Size(73, 25);
            this.seriesLabel.TabIndex = 23;
            this.seriesLabel.Text = "Series";
            // 
            // prescriptionIdLabel
            // 
            this.prescriptionIdLabel.AutoSize = true;
            this.prescriptionIdLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.prescriptionIdLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.prescriptionIdLabel.Location = new System.Drawing.Point(145, 66);
            this.prescriptionIdLabel.Name = "prescriptionIdLabel";
            this.prescriptionIdLabel.Size = new System.Drawing.Size(152, 25);
            this.prescriptionIdLabel.TabIndex = 22;
            this.prescriptionIdLabel.Text = "Prescription ID";
            // 
            // deleteButton
            // 
            this.deleteButton.AllowAnimations = true;
            this.deleteButton.AllowMouseEffects = true;
            this.deleteButton.AllowToggling = false;
            this.deleteButton.AnimationSpeed = 200;
            this.deleteButton.AutoGenerateColors = false;
            this.deleteButton.AutoRoundBorders = false;
            this.deleteButton.AutoSizeLeftIcon = true;
            this.deleteButton.AutoSizeRightIcon = true;
            this.deleteButton.BackColor = System.Drawing.Color.Transparent;
            this.deleteButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteButton.BackgroundImage")));
            this.deleteButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.ButtonText = "Delete";
            this.deleteButton.ButtonTextMarginLeft = 0;
            this.deleteButton.ColorContrastOnClick = 45;
            this.deleteButton.ColorContrastOnHover = 45;
            this.deleteButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.deleteButton.CustomizableEdges = borderEdges1;
            this.deleteButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deleteButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.deleteButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.deleteButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.deleteButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deleteButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deleteButton.IconMarginLeft = 11;
            this.deleteButton.IconPadding = 10;
            this.deleteButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deleteButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deleteButton.IconSize = 25;
            this.deleteButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.IdleBorderRadius = 1;
            this.deleteButton.IdleBorderThickness = 1;
            this.deleteButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.IdleIconLeftImage = null;
            this.deleteButton.IdleIconRightImage = null;
            this.deleteButton.IndicateFocus = false;
            this.deleteButton.Location = new System.Drawing.Point(566, 287);
            this.deleteButton.Name = "deleteButton";
            this.deleteButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteButton.OnDisabledState.BorderRadius = 1;
            this.deleteButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnDisabledState.BorderThickness = 1;
            this.deleteButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteButton.OnDisabledState.IconLeftImage = null;
            this.deleteButton.OnDisabledState.IconRightImage = null;
            this.deleteButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.onHoverState.BorderRadius = 1;
            this.deleteButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.onHoverState.BorderThickness = 1;
            this.deleteButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deleteButton.onHoverState.IconLeftImage = null;
            this.deleteButton.onHoverState.IconRightImage = null;
            this.deleteButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnIdleState.BorderRadius = 1;
            this.deleteButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnIdleState.BorderThickness = 1;
            this.deleteButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.deleteButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.deleteButton.OnIdleState.IconLeftImage = null;
            this.deleteButton.OnIdleState.IconRightImage = null;
            this.deleteButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnPressedState.BorderRadius = 1;
            this.deleteButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteButton.OnPressedState.BorderThickness = 1;
            this.deleteButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.deleteButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deleteButton.OnPressedState.IconLeftImage = null;
            this.deleteButton.OnPressedState.IconRightImage = null;
            this.deleteButton.Size = new System.Drawing.Size(75, 40);
            this.deleteButton.TabIndex = 20;
            this.deleteButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.deleteButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deleteButton.TextMarginLeft = 0;
            this.deleteButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.deleteButton.UseDefaultRadiusAndThickness = true;
            this.deleteButton.Click += new System.EventHandler(this.deleteButton_Click);
            // 
            // updateButton
            // 
            this.updateButton.AllowAnimations = true;
            this.updateButton.AllowMouseEffects = true;
            this.updateButton.AllowToggling = false;
            this.updateButton.AnimationSpeed = 200;
            this.updateButton.AutoGenerateColors = false;
            this.updateButton.AutoRoundBorders = false;
            this.updateButton.AutoSizeLeftIcon = true;
            this.updateButton.AutoSizeRightIcon = true;
            this.updateButton.BackColor = System.Drawing.Color.Transparent;
            this.updateButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("updateButton.BackgroundImage")));
            this.updateButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.ButtonText = "Update";
            this.updateButton.ButtonTextMarginLeft = 0;
            this.updateButton.ColorContrastOnClick = 45;
            this.updateButton.ColorContrastOnHover = 45;
            this.updateButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.updateButton.CustomizableEdges = borderEdges2;
            this.updateButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.updateButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.updateButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.updateButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.updateButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.updateButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.updateButton.IconMarginLeft = 11;
            this.updateButton.IconPadding = 10;
            this.updateButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.updateButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.updateButton.IconSize = 25;
            this.updateButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.IdleBorderRadius = 1;
            this.updateButton.IdleBorderThickness = 1;
            this.updateButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.IdleIconLeftImage = null;
            this.updateButton.IdleIconRightImage = null;
            this.updateButton.IndicateFocus = false;
            this.updateButton.Location = new System.Drawing.Point(456, 287);
            this.updateButton.Name = "updateButton";
            this.updateButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.OnDisabledState.BorderRadius = 1;
            this.updateButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnDisabledState.BorderThickness = 1;
            this.updateButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.OnDisabledState.IconLeftImage = null;
            this.updateButton.OnDisabledState.IconRightImage = null;
            this.updateButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.onHoverState.BorderRadius = 1;
            this.updateButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.onHoverState.BorderThickness = 1;
            this.updateButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.updateButton.onHoverState.IconLeftImage = null;
            this.updateButton.onHoverState.IconRightImage = null;
            this.updateButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnIdleState.BorderRadius = 1;
            this.updateButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnIdleState.BorderThickness = 1;
            this.updateButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.updateButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.updateButton.OnIdleState.IconLeftImage = null;
            this.updateButton.OnIdleState.IconRightImage = null;
            this.updateButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.BorderRadius = 1;
            this.updateButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnPressedState.BorderThickness = 1;
            this.updateButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.updateButton.OnPressedState.IconLeftImage = null;
            this.updateButton.OnPressedState.IconRightImage = null;
            this.updateButton.Size = new System.Drawing.Size(75, 40);
            this.updateButton.TabIndex = 19;
            this.updateButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.updateButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.updateButton.TextMarginLeft = 0;
            this.updateButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.updateButton.UseDefaultRadiusAndThickness = true;
            this.updateButton.Click += new System.EventHandler(this.updateButton_Click);
            // 
            // addButton
            // 
            this.addButton.AllowAnimations = true;
            this.addButton.AllowMouseEffects = true;
            this.addButton.AllowToggling = false;
            this.addButton.AnimationSpeed = 200;
            this.addButton.AutoGenerateColors = false;
            this.addButton.AutoRoundBorders = false;
            this.addButton.AutoSizeLeftIcon = true;
            this.addButton.AutoSizeRightIcon = true;
            this.addButton.BackColor = System.Drawing.Color.Transparent;
            this.addButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addButton.BackgroundImage")));
            this.addButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.ButtonText = "Add";
            this.addButton.ButtonTextMarginLeft = 0;
            this.addButton.ColorContrastOnClick = 45;
            this.addButton.ColorContrastOnHover = 45;
            this.addButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.addButton.CustomizableEdges = borderEdges3;
            this.addButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.addButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.addButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addButton.IconMarginLeft = 11;
            this.addButton.IconPadding = 10;
            this.addButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addButton.IconSize = 25;
            this.addButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.IdleBorderRadius = 1;
            this.addButton.IdleBorderThickness = 1;
            this.addButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.IdleIconLeftImage = null;
            this.addButton.IdleIconRightImage = null;
            this.addButton.IndicateFocus = false;
            this.addButton.Location = new System.Drawing.Point(347, 287);
            this.addButton.Name = "addButton";
            this.addButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addButton.OnDisabledState.BorderRadius = 1;
            this.addButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnDisabledState.BorderThickness = 1;
            this.addButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addButton.OnDisabledState.IconLeftImage = null;
            this.addButton.OnDisabledState.IconRightImage = null;
            this.addButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.onHoverState.BorderRadius = 1;
            this.addButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.onHoverState.BorderThickness = 1;
            this.addButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addButton.onHoverState.IconLeftImage = null;
            this.addButton.onHoverState.IconRightImage = null;
            this.addButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnIdleState.BorderRadius = 1;
            this.addButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnIdleState.BorderThickness = 1;
            this.addButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.addButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.addButton.OnIdleState.IconLeftImage = null;
            this.addButton.OnIdleState.IconRightImage = null;
            this.addButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnPressedState.BorderRadius = 1;
            this.addButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addButton.OnPressedState.BorderThickness = 1;
            this.addButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.addButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addButton.OnPressedState.IconLeftImage = null;
            this.addButton.OnPressedState.IconRightImage = null;
            this.addButton.Size = new System.Drawing.Size(75, 40);
            this.addButton.TabIndex = 18;
            this.addButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addButton.TextMarginLeft = 0;
            this.addButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.addButton.UseDefaultRadiusAndThickness = true;
            this.addButton.Click += new System.EventHandler(this.addButton_Click);
            // 
            // backButton
            // 
            this.backButton.AllowAnimations = true;
            this.backButton.AllowMouseEffects = true;
            this.backButton.AllowToggling = false;
            this.backButton.AnimationSpeed = 200;
            this.backButton.AutoGenerateColors = false;
            this.backButton.AutoRoundBorders = false;
            this.backButton.AutoSizeLeftIcon = true;
            this.backButton.AutoSizeRightIcon = true;
            this.backButton.BackColor = System.Drawing.Color.Transparent;
            this.backButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("backButton.BackgroundImage")));
            this.backButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.ButtonText = "Back";
            this.backButton.ButtonTextMarginLeft = 0;
            this.backButton.ColorContrastOnClick = 45;
            this.backButton.ColorContrastOnHover = 45;
            this.backButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.backButton.CustomizableEdges = borderEdges4;
            this.backButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.backButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.backButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.backButton.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.backButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.backButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.backButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.backButton.IconMarginLeft = 11;
            this.backButton.IconPadding = 10;
            this.backButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.backButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.backButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.backButton.IconSize = 25;
            this.backButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.IdleBorderRadius = 1;
            this.backButton.IdleBorderThickness = 1;
            this.backButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.IdleIconLeftImage = null;
            this.backButton.IdleIconRightImage = null;
            this.backButton.IndicateFocus = false;
            this.backButton.Location = new System.Drawing.Point(12, 12);
            this.backButton.Name = "backButton";
            this.backButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.backButton.OnDisabledState.BorderRadius = 1;
            this.backButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnDisabledState.BorderThickness = 1;
            this.backButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.backButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.backButton.OnDisabledState.IconLeftImage = null;
            this.backButton.OnDisabledState.IconRightImage = null;
            this.backButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.onHoverState.BorderRadius = 1;
            this.backButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.onHoverState.BorderThickness = 1;
            this.backButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.backButton.onHoverState.IconLeftImage = null;
            this.backButton.onHoverState.IconRightImage = null;
            this.backButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnIdleState.BorderRadius = 1;
            this.backButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnIdleState.BorderThickness = 1;
            this.backButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.backButton.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.backButton.OnIdleState.IconLeftImage = null;
            this.backButton.OnIdleState.IconRightImage = null;
            this.backButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnPressedState.BorderRadius = 1;
            this.backButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.backButton.OnPressedState.BorderThickness = 1;
            this.backButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.backButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.backButton.OnPressedState.IconLeftImage = null;
            this.backButton.OnPressedState.IconRightImage = null;
            this.backButton.Size = new System.Drawing.Size(75, 40);
            this.backButton.TabIndex = 17;
            this.backButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.backButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.backButton.TextMarginLeft = 0;
            this.backButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.backButton.UseDefaultRadiusAndThickness = true;
            this.backButton.Click += new System.EventHandler(this.backButton_Click);
            // 
            // patientIdLabel
            // 
            this.patientIdLabel.AutoSize = true;
            this.patientIdLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.5F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.patientIdLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(179)))), ((int)(((byte)(74)))), ((int)(((byte)(0)))));
            this.patientIdLabel.Location = new System.Drawing.Point(145, 193);
            this.patientIdLabel.Name = "patientIdLabel";
            this.patientIdLabel.Size = new System.Drawing.Size(105, 25);
            this.patientIdLabel.TabIndex = 31;
            this.patientIdLabel.Text = "Patient ID";
            // 
            // patientIdTextbox
            // 
            this.patientIdTextbox.AcceptsReturn = false;
            this.patientIdTextbox.AcceptsTab = false;
            this.patientIdTextbox.AnimationSpeed = 200;
            this.patientIdTextbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.patientIdTextbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.patientIdTextbox.BackColor = System.Drawing.Color.Transparent;
            this.patientIdTextbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("patientIdTextbox.BackgroundImage")));
            this.patientIdTextbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.patientIdTextbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.patientIdTextbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.patientIdTextbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.patientIdTextbox.BorderRadius = 1;
            this.patientIdTextbox.BorderThickness = 1;
            this.patientIdTextbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.patientIdTextbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.patientIdTextbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.patientIdTextbox.DefaultText = "";
            this.patientIdTextbox.FillColor = System.Drawing.Color.White;
            this.patientIdTextbox.HideSelection = true;
            this.patientIdTextbox.IconLeft = null;
            this.patientIdTextbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.patientIdTextbox.IconPadding = 10;
            this.patientIdTextbox.IconRight = null;
            this.patientIdTextbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.patientIdTextbox.Lines = new string[0];
            this.patientIdTextbox.Location = new System.Drawing.Point(347, 193);
            this.patientIdTextbox.MaxLength = 32767;
            this.patientIdTextbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.patientIdTextbox.Modified = false;
            this.patientIdTextbox.Multiline = false;
            this.patientIdTextbox.Name = "patientIdTextbox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.patientIdTextbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.patientIdTextbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.patientIdTextbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.patientIdTextbox.OnIdleState = stateProperties16;
            this.patientIdTextbox.Padding = new System.Windows.Forms.Padding(3);
            this.patientIdTextbox.PasswordChar = '\0';
            this.patientIdTextbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.patientIdTextbox.PlaceholderText = "Enter text";
            this.patientIdTextbox.ReadOnly = false;
            this.patientIdTextbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.patientIdTextbox.SelectedText = "";
            this.patientIdTextbox.SelectionLength = 0;
            this.patientIdTextbox.SelectionStart = 0;
            this.patientIdTextbox.ShortcutsEnabled = true;
            this.patientIdTextbox.Size = new System.Drawing.Size(294, 28);
            this.patientIdTextbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.patientIdTextbox.TabIndex = 32;
            this.patientIdTextbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.patientIdTextbox.TextMarginBottom = 0;
            this.patientIdTextbox.TextMarginLeft = 3;
            this.patientIdTextbox.TextMarginTop = 0;
            this.patientIdTextbox.TextPlaceholder = "Enter text";
            this.patientIdTextbox.UseSystemPasswordChar = false;
            this.patientIdTextbox.WordWrap = true;
            // 
            // Prescriptions
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(26)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(782, 553);
            this.Controls.Add(this.patientIdTextbox);
            this.Controls.Add(this.patientIdLabel);
            this.Controls.Add(this.prescriptionsGridView);
            this.Controls.Add(this.issueDatePicker);
            this.Controls.Add(this.numberTextbox);
            this.Controls.Add(this.seriesTextbox);
            this.Controls.Add(this.prescriptionIdTextbox);
            this.Controls.Add(this.issueDateLabel);
            this.Controls.Add(this.numberLabel);
            this.Controls.Add(this.seriesLabel);
            this.Controls.Add(this.prescriptionIdLabel);
            this.Controls.Add(this.deleteButton);
            this.Controls.Add(this.updateButton);
            this.Controls.Add(this.addButton);
            this.Controls.Add(this.backButton);
            this.Name = "Prescriptions";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "MediCode";
            this.Load += new System.EventHandler(this.Prescriptions_Load);
            ((System.ComponentModel.ISupportInitialize)(this.prescriptionsGridView)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView prescriptionsGridView;
        private Bunifu.UI.WinForms.BunifuDatePicker issueDatePicker;
        private Bunifu.UI.WinForms.BunifuTextBox numberTextbox;
        private Bunifu.UI.WinForms.BunifuTextBox seriesTextbox;
        private Bunifu.UI.WinForms.BunifuTextBox prescriptionIdTextbox;
        private System.Windows.Forms.Label issueDateLabel;
        private System.Windows.Forms.Label numberLabel;
        private System.Windows.Forms.Label seriesLabel;
        private System.Windows.Forms.Label prescriptionIdLabel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton deleteButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton updateButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton backButton;
        private System.Windows.Forms.Label patientIdLabel;
        private Bunifu.UI.WinForms.BunifuTextBox patientIdTextbox;
    }
}